import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './components/App';
import ToastProvider from './components/ToastProvider';
import '../index.css';

const saved = localStorage.getItem('theme');
if (saved === 'dark') {
  document.documentElement.classList.add('dark');
}

// Bootstraps the main renderer process. This simply mounts the React
// application into the root div generated by Electron.

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(
    <ToastProvider>
      <App />
    </ToastProvider>,
  );
}
