import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './components/App';
import '../index.css';

const saved = localStorage.getItem('theme');
if (saved) {
  document.documentElement.setAttribute('data-theme', saved);
}

// Bootstraps the main renderer process. This simply mounts the React
// application into the root div generated by Electron.

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(<App />);
}
