// Utility responsible for packaging a project directory into a distributable
// resource pack zip.  The output always includes a minimal `pack.mcmeta` file.

import fs from 'fs';
import archiver from 'archiver';
import { packFormatForVersion } from '../minecraft/packFormat';

// Export the contents of `projectPath` into `outPath` as a zip archive.
export function exportPack(
projectPath: string,
outPath: string,
version = '1.21.1',
): Promise<void> {
  return new Promise((resolve, reject) => {
    const output = fs.createWriteStream(outPath);
    const archive = archiver('zip', { zlib: { level: 9 } });

    output.on('close', () => resolve());
    archive.on('error', err => reject(err));

    archive.pipe(output);
    archive.directory(projectPath, false);
    // Add a default pack.mcmeta so Minecraft recognises the pack.
    const format = packFormatForVersion(version) ?? 15;
    const mcmeta = {
      pack: { pack_format: format, description: 'Generated by mc-pack-tool' },
    };
    archive.append(JSON.stringify(mcmeta, null, 2), { name: 'pack.mcmeta' });
    archive.finalize();
  });
}
