import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './components/App';
import ToastProvider from './components/providers/ToastProvider';
import { HashRouter } from 'react-router-dom';
import './styles/index.css';
import { applyTheme } from './utils/theme';

import loader from '@monaco-editor/loader';
import * as monaco from 'monaco-editor';

loader.config({ monaco });

// eslint-disable-next-line @typescript-eslint/no-unused-vars
loader.init().then((_monacoInstance: typeof monaco) => {
  // it loaded
});

window.electronAPI?.getTheme().then((t) => {
  applyTheme(t);
});

// Bootstraps the main renderer process. This simply mounts the React
// application into the root div generated by Electron.

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(
    <HashRouter>
      <ToastProvider>
        <App />
      </ToastProvider>
    </HashRouter>
  );
}
