import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './components/App';
import ToastProvider from './components/ToastProvider';
import './styles/index.css';
import { applyTheme } from './utils/theme';

window.electronAPI?.getTheme().then((t) => {
  applyTheme(t);
});

// Bootstraps the main renderer process. This simply mounts the React
// application into the root div generated by Electron.

const container = document.getElementById('root');
if (container) {
  const root = createRoot(container);
  root.render(
    <ToastProvider>
      <App />
    </ToastProvider>
  );
}
